### ISSUE TITLE
improve usability 

### ISSUE THREAD

**Issue by AhmadHakami** [mush42/tesseract-arabic#1]
this repository appears to be great and impressive but the main issue lies in its lack of clear explanation in the `readme.md` file. consequently others may encounter difficulties when trying to use it for training due to unclear steps

could you please rewrite it and also test for any error messages fixing them if found?

thanks

**Comment by mush42** [comment]
Hi @AhmadHakami 

Thanks for your interest in the repo.

I moved on from `Tesseract` to more modern OCR techniques. I should mark this repo as archived to communicate this fact.

Nevertheless, I'm ready to revive it if enough interest exists.

Best
Musharraf

**Comment by AhmadHakami** [comment]
yes please proceed accordingly

thanks in advance!

**Comment by AhmadHakami** [comment]
any updates?

**Comment by mush42** [comment]
@AhmadHakami  I don't have enough time for working on this. I'm currently focusing on [libtashkeel](https://github.com/mush42/libtashkeel) and [Sonata](https://github.com/mush42/sonata)
